select nombre from producto;
select nombre,precio from producto;
select * from producto;
select nombre, precio as precio_euros, precio * 1.1422 as precio_dolar from producto;
select nombre as nom_de_producto,precio as euros, precio *1.1422 as dolars from producto;
select upper(nombre) as NOM_MAYÚSCULA, precio as PRECIO from producto;
select lower(nombre) as NOM_MINÚSCULA,precio as PRECIO from producto;
select nombre, upper(left(nombre,2)) from fabricante;
select nombre, round(precio,0) from producto;
select nombre, truncate(precio,0) as precio from producto;
select fabricante.codigo from fabricante join producto on fabricante.codigo = producto.codigo_fabricante;
select distinct fabricante.codigo from fabricante join producto on fabricante.codigo = producto.codigo_fabricante;
select nombre from fabricante order by nombre ASC;
select nombre from fabricante order by nombre DESC;
select nombre from producto order by nombre asc,precio desc;
select * from fabricante limit 5;
select * from fabricante limit 3,2;
select nombre,precio from producto order by precio limit 1;
select nombre,precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante = 2;
select p.nombre,precio,f.nombre as fabricante from producto p left join fabricante f on p.codigo_fabricante=f.codigo;
select p.nombre,precio,f.nombre as fabricante from producto p left join fabricante f on p.codigo_fabricante=f.codigo order by f.nombre asc;
select p.codigo as codigo_producto ,p.nombre,f.codigo as codigo_fabricante,f.nombre as fabricante from producto p left join fabricante f on p.codigo_fabricante=f.codigo;
select p.nombre,precio,f.nombre from producto p join fabricante f on p.codigo_fabricante=f.codigo where precio = (select min(precio) from producto);
select p.nombre,precio,f.nombre from producto p join fabricante f on p.codigo_fabricante=f.codigo where precio = (select max(precio) from producto);
select p.codigo ,p.nombre, precio, f.codigo, f.nombre as fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre = 'Lenovo';
select p.codigo ,p.nombre, precio, f.codigo, f.nombre as fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre = 'Crucial' and precio > 200 ;
select p.codigo ,p.nombre, precio, f.codigo, f.nombre as fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre = 'Asus' or f.nombre = 'Hewlett-Packard' or f.nombre = 'Seagate';
select p.codigo ,p.nombre, precio, f.codigo, f.nombre as fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre in('Asus','Hewlett-Packard','Seagate');
select p.nombre, precio from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre LIKE '%e';
select p.nombre, precio from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre LIKE '%w%';
select p.nombre, precio,f.nombre from producto p join fabricante f on p.codigo_fabricante=f.codigo where precio>=180 order by precio desc, p.nombre asc;
select  distinct f.codigo,f.nombre from producto p left join fabricante f on p.codigo_fabricante=f.codigo;
select f.codigo,f.nombre,p.nombre from producto p right join fabricante f on p.codigo_fabricante=f.codigo;
select f.codigo,f.nombre from producto p right join fabricante f on p.codigo_fabricante=f.codigo where p.codigo_fabricante is null;
select * from producto where codigo_fabricante= (select codigo from fabricante where nombre= 'Lenovo');
select * from producto where precio = (select max(precio) from producto where codigo_fabricante= (select codigo from fabricante where nombre= 'Lenovo'));
select p.nombre,max(precio) from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre='Lenovo';
select p.nombre,min(precio) from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre='Hewlett-Packard';
select p.nombre from producto p join fabricante f on p.codigo_fabricante=f.codigo where precio >= (select max(precio) from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre='Lenovo');
select p.codigo,p.nombre,p.precio from producto p join fabricante f on p.codigo_fabricante=f.codigo where precio > (select avg(precio) from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre='Asus') and f.nombre='Asus';
select apellido1,apellido2,nombre from persona order by apellido1 asc,apellido2 asc,nombre asc;
select nombre,apellido1,apellido2 from persona where telefono is null and tipo='alumno';
select nombre,apellido1,apellido2 from persona where year(fecha_nacimiento)= 1999 and tipo='alumno';
select * from persona where tipo = 'profesor' and telefono is null and nif like '%K';
select * from asignatura where cuatrimestre=1 and id_grado=7 and curso=3;
select p.apellido1,p.apellido2,p.nombre,d.nombre from persona p join profesor pr on p.id=pr.id_profesor join departamento d on pr.id_departamento=d.id order by p.apellido1 asc,p.apellido2 asc,p.nombre asc;
select a.nombre, c.anyo_inicio,c.anyo_fin from persona p join alumno_se_matricula_asignatura al on p.id = al.id_alumno join curso_escolar c on c.id=al.id_curso_escolar join asignatura a on al.id_asignatura=a.id where p.nif='26902806M';
select distinct d.nombre from departamento d join profesor p on d.id=p.id_departamento join asignatura a on p.id_profesor=a.id_profesor join grado g on a.id_grado=g.id where g.nombre='Grado en Ingeniería Informática (Plan 2015)';
select distinct p.id,p.nif,p.nombre, p.apellido1,p.apellido2  from persona p join alumno_se_matricula_asignatura al on p.id=al.id_alumno join asignatura a on al.id_asignatura=a.id join curso_escolar c on al.id_curso_escolar=c.id where c.anyo_inicio='2018' and c.anyo_fin='2019'; 
select p.apellido1,p.apellido2,p.nombre,d.nombre from persona p left join profesor pr  on p.id=pr.id_profesor left join departamento d on pr.id_departamento=d.id order by d.nombre asc ,p.apellido1 asc ,p.apellido2 asc,p.nombre asc;
select d.nombre,p.apellido1,p.apellido2,p.nombre from persona p join profesor pr  on p.id=pr.id_profesor right join departamento d on pr.id_departamento=d.id;
select d.nombre,pe.apellido1,pe.apellido2,pe.nombre from profesor p right join departamento d on p.id_departamento=d.id left join persona pe on p.id_profesor=pe.id where p.id_profesor is null;
select * from profesor pr left join asignatura a on a.id_profesor=pr.id_profesor left join persona p on pr.id_profesor=p.id where a.id is null; 
select a.nombre,pr.id_profesor from asignatura a left join profesor pr on a.id_profesor=pr.id_profesor left join persona p on pr.id_profesor=p.id where pr.id_profesor is null; 
SELECT DISTINCT d.nombre FROM departamento d JOIN profesor pr ON d.id = pr.id_departamento LEFT JOIN  asignatura a ON pr.id_profesor = a.id_profesor WHERE a.id_profesor IS NULL;
select count(id) from persona where tipo = 'alumno';
select count(id) from persona where tipo = 'alumno' and year(fecha_nacimiento)='1999';
select d.nombre,count(pr.id_profesor) as numero_profesores from persona p join profesor pr on p.id=pr.id_profesor join departamento d on pr.id_departamento=d.id group by d.id order by numero_profesores desc;
select d.nombre,count(pr.id_profesor) as numero_profesores from persona p join profesor pr on p.id=pr.id_profesor right join departamento d on pr.id_departamento=d.id group by d.id order by numero_profesores desc;
select g.nombre,count(a.id) from asignatura a right join grado g on a.id_grado=g.id group by g.id order by count(a.id) desc;
select g.nombre,count(a.id) as numero_asignaturas from asignatura a join grado g on a.id_grado=g.id group by g.id having count(a.id) > 40;
select g.nombre,a.tipo,count(a.id) as numero_asignaturas from asignatura a join grado g on a.id_grado=g.id group by g.id,a.tipo;
select c.anyo_inicio,count(a.id) as numero_alumnos from persona p join alumno_se_matricula_asignatura al on p.id= al.id_alumno join asignatura a on al.id_asignatura=a.id join curso_escolar c on al.id_curso_escolar=c.id group by c.anyo_inicio;
select p.id,p.nombre,p.apellido1,p.apellido2, count(a.id) as numero_asignaturas from persona p join profesor pr on p.id=pr.id_profesor left join asignatura a on pr.id_profesor=a.id_profesor group by pr.id_profesor order by numero_asignaturas desc;
select * from persona where fecha_nacimiento = (select max(fecha_nacimiento) from persona where tipo='alumno');
SELECT DISTINCT p.apellido1, p.apellido2,p.nombre FROM persona p JOIN profesor pr ON p.id = pr.id_profesor LEFT JOIN  asignatura a ON  a.id_profesor = pr.id_profesor WHERE a.id_profesor IS NULL;
